export const CIRCUIT_SVG_MAP: Record<string, string> = {
    'monza':          'monza-7',
    'monaco':         'monaco-6',
    'silverstone':    'silverstone-8',
    'spa':            'spa-francorchamps-4',
    'bahrain':        'bahrain-1',
    'jeddah':         'jeddah-1',
    'albert_park':    'melbourne-2',
    'suzuka':         'suzuka-2',
    'shanghai':       'shanghai-1',
    'miami':          'miami-1',
    'imola':          'imola-3',
    'villeneuve':     'montreal-6',
    'red_bull_ring':  'spielberg-3',
    'hungaroring':    'hungaroring-3',
    'zandvoort':      'zandvoort-5',
    'baku':           'baku-1',
    'marina_bay':     'marina-bay-4',
    'americas':       'austin-1',
    'rodriguez':      'mexico-city-3',
    'interlagos':     'interlagos-2',
    'vegas':          'las-vegas-1',
    'losail':         'lusail-1',
    'yas_marina':     'yas-marina-2',
    'madring':        'madring-1',
    'catalunya':      'catalunya-6'
  };